let properties = [
    {
        "id_property": 906433,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "false",
        "for_rent": "true",
        "for_transfer": "false",
        "id_property_type": "1",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "4",
        "region_label": "Atlántico",
        "id_city": "82",
        "city_label": "Barranquilla",
        "id_location": 0,
        "location_label": "",
        "id_zone": "96589",
        "zone_label": "Prado",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "CASA COMERCIAL ESQUINA",
        "address": "Carrera 55 #74-02, barrio El Prado",
        "area": "487",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "270",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "270",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "0",
        "sale_price_label": "$0",
        "rent_price": "8000000",
        "rent_price_label": "$8.000.000",
        "bedrooms": "5",
        "bathrooms": "5",
        "garages": "1",
        "floor": "",
        "stratum": "5",
        "observations": "<p>Excelente casa comercial de esquina, ubicada en el sector corporativo y financiero de mayor proyecci&oacute;n en la ciudad de Baranquilla.&nbsp; La casa tiene uso comercial autorizado&nbsp; actividades de comercializacion de bienes y servicios, cuenta con 9 parqueaderos propios para visitantes.&nbsp; La negociaci&oacute;n es directa con el propietario.</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "1",
        "status_on_page_label": "Active",
        "map": "11.000807166615152,-74.80189561843873",
        "latitude": "11.000807166615152",
        "longitude": "-74.80189561843873",
        "building_date": "",
        "network_share": true,
        "visits": "6",
        "created_at": "2018-10-29 12:34:58",
        "updated_at": "2018-11-13 16:42:42",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "730529",
            "id_image": 29558978,
            "url": "https://images.wasi.co/inmuebles/b15905120181029122950.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120181029122950.jpg",
            "description": "",
            "position": "1"
        },
        "galleries": [
            {
                "0": {
                    "id": 29558978,
                    "url": "https://images.wasi.co/inmuebles/b15905120181029122950.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120181029122950.jpg",
                    "description": "",
                    "position": "1"
                },
                "1": {
                    "id": 29558979,
                    "url": "https://images.wasi.co/inmuebles/b15905220181029122955.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905220181029122955.jpg",
                    "description": "",
                    "position": "2"
                },
                "2": {
                    "id": 29558980,
                    "url": "https://images.wasi.co/inmuebles/b15905320181029122958.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905320181029122958.jpg",
                    "description": "",
                    "position": "3"
                },
                "3": {
                    "id": 29558981,
                    "url": "https://images.wasi.co/inmuebles/b15905420181029123000.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905420181029123000.jpg",
                    "description": "",
                    "position": "4"
                },
                "4": {
                    "id": 29558982,
                    "url": "https://images.wasi.co/inmuebles/b15905520181029123003.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905520181029123003.jpg",
                    "description": "",
                    "position": "5"
                },
                "5": {
                    "id": 29558983,
                    "url": "https://images.wasi.co/inmuebles/b15905620181029123005.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905620181029123005.jpg",
                    "description": "",
                    "position": "6"
                },
                "6": {
                    "id": 29558984,
                    "url": "https://images.wasi.co/inmuebles/b15905720181029123007.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905720181029123007.jpg",
                    "description": "",
                    "position": "7"
                },
                "7": {
                    "id": 29558985,
                    "url": "https://images.wasi.co/inmuebles/b15905820181029123010.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905820181029123010.jpg",
                    "description": "",
                    "position": "8"
                },
                "8": {
                    "id": 29558986,
                    "url": "https://images.wasi.co/inmuebles/b15905920181029123013.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905920181029123013.jpg",
                    "description": "",
                    "position": "9"
                },
                "id": 730529
            }
        ],
        "features": {
            "internal": [],
            "external": [
                {
                    "id": 40,
                    "nombre": "Terraza",
                    "name": ""
                },
                {
                    "id": 67,
                    "nombre": "Zona comercial",
                    "name": ""
                }
            ]
        }
    },
    {
        "id_property": 691358,
        "id_company": 2426798,
        "id_user": "32018",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "12",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "CASA HOTEL ORCHIDS",
        "address": "CARRERA 5 Nº 10-47",
        "area": "333.50",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "585.10",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "10000000000",
        "sale_price_label": "$10.000.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "2",
        "stratum": "",
        "observations": "<p>Casa hotel de 7 habitaciones ba&ntilde;os con jacuzzi, salon de recepci&ograve;n, comedor cocina, patio interno, hall de acceso, area social, jardin interno fuente, cuarto de calentadores.&nbsp; excelente ubicacion&nbsp; inmueble de interes cultural vias de acceso como la avenida calle 13, la cale 6,la carrera 7 buen estado de conservaci&ograve;n. para uso comercial y de servicios.</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "18",
        "created_at": "2018-06-08 17:11:18",
        "updated_at": "2018-06-08 17:16:37",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "569750",
            "id_image": 23000579,
            "url": "https://images.wasi.co/inmuebles/b15905120180608050319.png",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180608050319.png",
            "description": "",
            "position": "1"
        },
        "galleries": [
            {
                "0": {
                    "id": 23000579,
                    "url": "https://images.wasi.co/inmuebles/b15905120180608050319.png",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180608050319.png",
                    "description": "",
                    "position": "1"
                },
                "1": {
                    "id": 23000580,
                    "url": "https://images.wasi.co/inmuebles/b15905220180608050333.png",
                    "url_big": "https://images.wasi.co/inmuebles/g15905220180608050333.png",
                    "description": "",
                    "position": "2"
                },
                "2": {
                    "id": 23000581,
                    "url": "https://images.wasi.co/inmuebles/b15905320180608050355.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905320180608050355.jpg",
                    "description": "",
                    "position": "3"
                },
                "3": {
                    "id": 23000582,
                    "url": "https://images.wasi.co/inmuebles/b15905420180608050355.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905420180608050355.jpg",
                    "description": "",
                    "position": "4"
                },
                "4": {
                    "id": 23000583,
                    "url": "https://images.wasi.co/inmuebles/b15905520180608050356.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905520180608050356.jpg",
                    "description": "",
                    "position": "5"
                },
                "5": {
                    "id": 23000584,
                    "url": "https://images.wasi.co/inmuebles/b15905620180608050356.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905620180608050356.jpg",
                    "description": "",
                    "position": "6"
                },
                "6": {
                    "id": 23000585,
                    "url": "https://images.wasi.co/inmuebles/b15905720180608050356.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905720180608050356.jpg",
                    "description": "",
                    "position": "7"
                },
                "id": 569750
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 685901,
        "id_company": 2426798,
        "id_user": "32018",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "3",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "LOCAL COMERCIAL ",
        "address": "CARERA 10 Nº 147-48 LOCAL 20 Y 21",
        "area": "",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "79",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "622000000",
        "sale_price_label": "$622.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p>LOCAL EN CENTRO COMECIAL PORTICO EN LA CIUDAD DE BOGOTA, LOCAL COMERCIAL DE ALTA VALORIZACION CON EXCELENTES VIAS DE ACCESO COMO LA AVENIDAD CARRERA 91 Y 92 LA AVENIDA SUBA, CONSTRUCCIONES EN EXCELENTE ESTADO, ES DE USO COMERCIAL Y DE SERVICIOS.&nbsp;</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "25",
        "created_at": "2018-06-07 16:05:13",
        "updated_at": "2018-06-07 16:09:24",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "568255",
            "id_image": 22948445,
            "url": "https://images.wasi.co/inmuebles/b15905120180607040549.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180607040549.jpg",
            "description": "",
            "position": "0"
        },
        "galleries": [
            {
                "0": {
                    "id": 22948445,
                    "url": "https://images.wasi.co/inmuebles/b15905120180607040549.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180607040549.jpg",
                    "description": "",
                    "position": "0"
                },
                "1": {
                    "id": 22948447,
                    "url": "https://images.wasi.co/inmuebles/b15905220180607040550.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905220180607040550.jpg",
                    "description": "",
                    "position": "1"
                },
                "id": 568255
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 684206,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "14",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "LOCAL COMERCIAL ",
        "address": "CARRERA 10 Nº147-48 LC19 CENTRO COMERCIAL PORTICO",
        "area": "",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "29",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "230000000",
        "sale_price_label": "$230.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p>LOCAL&nbsp; DE ALTA VALORIZACION, CON EXCELENTES VIAS DE ACCESO COMO LA AVENIDA CARRERA 91 - 92, Y AVENIDA SUBA, CONSTRUCCION EN EXCELENTE ESTADO DE CONSERVACION, IDEAL PARA USO COMERCIAL Y DE SERVICIOS&nbsp;</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "27",
        "created_at": "2018-06-06 17:39:18",
        "updated_at": "0000-00-00 00:00:00",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "566663",
            "id_image": 22903479,
            "url": "https://images.wasi.co/inmuebles/b15905120180606053854.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606053854.jpg",
            "description": "",
            "position": "0"
        },
        "galleries": [
            {
                "0": {
                    "id": 22903479,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606053854.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606053854.jpg",
                    "description": "",
                    "position": "0"
                },
                "1": {
                    "id": 22903480,
                    "url": "https://images.wasi.co/inmuebles/b15905220180606053854.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905220180606053854.jpg",
                    "description": "",
                    "position": "1"
                },
                "id": 566663
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 640584,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "3",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "LOCAL CENTRO COMERCIAL PORTAL 80",
        "address": "AV. CALLE 80 N° 100 -52 LC NV2-122 CENTRO COMERCIAL PORTAL 80",
        "area": "",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "40.60",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "1450000000",
        "sale_price_label": "$1.450.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p>DESCRIPCION DEL INMUEBLE:</p>\n\n<p>LOCAL COMERCIAL RENTABLE DE ALTA VALORIZACION, CON EXCELENTES VIAS DE ACCESO COMO LA AVRNIDA CALLE 80 Y LA CARRERA 102, CONSTRUCCIONES EN EXCELENTE ESTADO DE CONSERVACION, PARA USO COMERCIAL Y DE SERVICIOS.</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "2",
        "created_at": "2018-05-26 12:59:16",
        "updated_at": "2018-06-06 16:33:24",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "554353",
            "id_image": 22898900,
            "url": "https://images.wasi.co/inmuebles/b15905120180606043059.png",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606043059.png",
            "description": "",
            "position": "0"
        },
        "galleries": [
            {
                "0": {
                    "id": 22898900,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606043059.png",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606043059.png",
                    "description": "",
                    "position": "0"
                },
                "1": {
                    "id": 22898901,
                    "url": "https://images.wasi.co/inmuebles/b15905320180606043227.png",
                    "url_big": "https://images.wasi.co/inmuebles/g15905320180606043227.png",
                    "description": "",
                    "position": "2"
                },
                "id": 554353
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 640578,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "3",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "LOCAL CENTRO COMERCIAL UNICENTRO ",
        "address": "CARRERA 111C N° 86-05 LC 219 - DS1 CENTRO COMERCIAL UNICENTRO DE OCCIDENTE",
        "area": "",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "51.47",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "1550000000",
        "sale_price_label": "$1.550.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p>DESCRIPCION DEL INMUEBLE:</p>\n\n<p>LOCAL COMERCIAL RENTABLE DE ALTA VALORIZACION, CON EXCELENTES VIAS DE ACCESO COMO LA CALLE 83,83BIS, Y LA CALLE 96, CONSTRUCCIONES EN EXCELENTE ESTADO PARA USO COMERCIAL Y DE SERVICIOS.&nbsp;</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "2",
        "created_at": "2018-05-26 12:50:00",
        "updated_at": "2018-06-06 16:43:25",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "554347",
            "id_image": 22899780,
            "url": "https://images.wasi.co/inmuebles/b15905120180606044202.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606044202.jpg",
            "description": "",
            "position": "0"
        },
        "galleries": [
            {
                "0": {
                    "id": 22899780,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606044202.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606044202.jpg",
                    "description": "",
                    "position": "0"
                },
                "id": 554347
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 640572,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "3",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "LOCALES COMERCIAL",
        "address": "TRANSV.  55 N° 98 -66 LC 215-216",
        "area": "",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "145.8",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "1200000000",
        "sale_price_label": "$1.200.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p>DESCRIPCION DEL INMUEBLE:</p>\n\n<p>LOCALES COMERCIALES&nbsp; RENTABLES DE ALTA VALORIZACION, CON EXCELENTES VIAS DE ACCESO COMO LA AV. CALLE 100, LA AV. SUBA,&nbsp;LA AV. NOS Y LA AUTOPISTA NORTE. CONSTRUCCIONES EN EXCELENTE ESTADO DE CONSERVACION, PARA USO COMERCIAL Y DE SERVICIOS.&nbsp;</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "2",
        "created_at": "2018-05-26 12:43:09",
        "updated_at": "2018-06-06 16:54:01",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "554340",
            "id_image": 22900720,
            "url": "https://images.wasi.co/inmuebles/b15905120180606045352.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606045352.jpg",
            "description": "",
            "position": "0"
        },
        "galleries": [
            {
                "0": {
                    "id": 22900720,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606045352.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606045352.jpg",
                    "description": "",
                    "position": "0"
                },
                "id": 554340
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 640561,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "3",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "LOCAL CENTRO COMERCIAL FUTURO",
        "address": "AV. CALLE 147 N° 19-50 LOCAL 6",
        "area": "",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "279",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "1800000000",
        "sale_price_label": "$1.800.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p>DESCRIPCION DEL INMUEBLE:</p>\n\n<p>LOCAL COMERCIAL RENTABLE DE ALTA VALORIZACION CON EXCELENTES VIAS DE ACCESO COMO LA AV. CALLE 147,140, LA AV. CALLE 134, AV. CRA 19 Y LA AUTOPISTA NORTE, CONSTRUCCIONES EN EXCELENTE ESTADO DE CONSERVACION, PARA USO COMERCIAL Y DE SERVICIOS</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "2",
        "created_at": "2018-05-26 12:31:30",
        "updated_at": "2018-06-06 17:51:26",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "554328",
            "id_image": 22904251,
            "url": "https://images.wasi.co/inmuebles/b15905120180606055049.png",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606055049.png",
            "description": "",
            "position": "1"
        },
        "galleries": [
            {
                "0": {
                    "id": 22904251,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606055049.png",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606055049.png",
                    "description": "",
                    "position": "1"
                },
                "1": {
                    "id": 22904252,
                    "url": "https://images.wasi.co/inmuebles/b15905220180606055052.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905220180606055052.jpg",
                    "description": "",
                    "position": "2"
                },
                "id": 554328
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 640552,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "16",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "EDIFICIO DE OFICINAS",
        "address": "CALLE 134 BIS N° 19 -75",
        "area": "245",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "585",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "6500000000",
        "sale_price_label": "$6.500.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "3",
        "stratum": "",
        "observations": "<p><u>DESCRIPCION DEL INMUEBLE:</u></p>\n\n<p>Edificio administrativo de alta valorizaci&oacute;n , con excelentes vias de acceso comola Av. Cra 19, la AV calle 134&nbsp; y autopista Norte. construcciones en excelente estado de conservaci&oacute;n, para uso comercial y de servicios.&nbsp;</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "2",
        "created_at": "2018-05-26 12:19:32",
        "updated_at": "2018-06-06 17:22:37",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "554321",
            "id_image": 22902588,
            "url": "https://images.wasi.co/inmuebles/b15905120180606052217.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606052217.jpg",
            "description": "",
            "position": "0"
        },
        "galleries": [
            {
                "0": {
                    "id": 22902588,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606052217.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606052217.jpg",
                    "description": "",
                    "position": "0"
                },
                "id": 554321
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    },
    {
        "id_property": 640383,
        "id_company": 2426798,
        "id_user": "24392",
        "for_sale": "true",
        "for_rent": "false",
        "for_transfer": "false",
        "id_property_type": "1",
        "id_country": "1",
        "country_label": "Colombia",
        "id_region": "15",
        "region_label": "Cundinamarca",
        "id_city": "794",
        "city_label": "Bogotá D.C.",
        "id_location": 0,
        "location_label": "",
        "id_zone": "0",
        "zone_label": "",
        "id_currency": "1",
        "iso_currency": "COP",
        "name_currency": "Pesos Colombianos",
        "title": "CASA  CON LOCAL COMERCIAL Y OFICINAS ",
        "address": "AV. CRA 24Nº 63F-62B 7 DE AGOSTO",
        "area": "121",
        "id_unit_area": "1",
        "unit_area_label": "M2",
        "built_area": "",
        "id_unit_built_area": "1",
        "unit_built_area_label": "M2",
        "private_area": "363.10",
        "id_unit_private_area": "1",
        "unit_private_area_label": "M2",
        "maintenance_fee": "0",
        "sale_price": "1250000000",
        "sale_price_label": "$1.250.000.000",
        "rent_price": "0",
        "rent_price_label": "$0",
        "bedrooms": "0",
        "bathrooms": "0",
        "garages": "0",
        "floor": "",
        "stratum": "",
        "observations": "<p><u>DESCRIPCION DEL INMUEBLE:&nbsp;</u>&nbsp; &nbsp;</p>\n\n<p>Casa de tres pisos con local comercial y oficinas rentables de alta valorizacion con excelente&nbsp; vias de acceso como la Av. cra 24, la Av. Calle 68, 63, y 72 la Av. NOS&nbsp;y la Caracas. contruccion en excelente estado de conservacion, para uso residencial, comercial y de servicios.</p>\n",
        "video": "",
        "id_property_condition": "2",
        "property_condition_label": "Used",
        "id_status_on_page": "3",
        "status_on_page_label": "Outstanding",
        "map": "",
        "latitude": "",
        "longitude": "",
        "building_date": "",
        "network_share": true,
        "visits": "2",
        "created_at": "2018-05-26 09:42:52",
        "updated_at": "2018-06-06 16:29:37",
        "reference": "",
        "comment": "",
        "id_rents_type": "4",
        "rents_type_label": "Monthly",
        "zip_code": "",
        "id_availability": "1",
        "availability_label": "Available",
        "id_publish_on_map": "3",
        "publish_on_map_label": "Post exact point",
        "label": "",
        "label_color": "",
        "owner": "own",
        "main_image": {
            "id_gallery": "554154",
            "id_image": 22898722,
            "url": "https://images.wasi.co/inmuebles/b15905120180606035456.jpg",
            "url_big": "https://images.wasi.co/inmuebles/g15905120180606035456.jpg",
            "description": "",
            "position": "1"
        },
        "galleries": [
            {
                "0": {
                    "id": 22898722,
                    "url": "https://images.wasi.co/inmuebles/b15905120180606035456.jpg",
                    "url_big": "https://images.wasi.co/inmuebles/g15905120180606035456.jpg",
                    "description": "",
                    "position": "1"
                },
                "id": 554154
            }
        ],
        "features": {
            "internal": [],
            "external": []
        }
    }
];

properties.forEach((property, index) => {
	property.id = index + 1;
});

export default properties;